### PR TITLE
Update multi selection

### PR DESCRIPTION
**Pull request by DJ-Raven**
This PR update multi selections I see Issue #7 comment by @remcopoelstra. So please review this. Thank you.

### CODE REVIEW

**Comment by steos** [comment]
Thanks a lot!

**Comment by DJ-Raven** [comment]
@steos Please update this line https://github.com/steos/jnafilechooser/blob/06992e3bd5968323ba925af973fb4f09fc17e911/api/src/main/java/jnafilechooser/api/WindowsFileChooser.java#L226

to match the changes from PR #21 

Apologies for the oversight I didn't check for the previous update before making my changes.

**Comment by steos** [comment]
isn't this already the current state on master?

**Comment by DJ-Raven** [comment]
Yes it's current on master.

**Comment by steos** [comment]
Sorry, I was not quite following. I think I got it now - so we should have as condition only this:

```java
if (!defaultFilename.isEmpty()) {
```
instead of 

```java
if (open && !defaultFilename.isEmpty()) { 
```

right?

**Comment by DJ-Raven** [comment]
> if (!defaultFilename.isEmpty()) {

yes

**Comment by steos** [comment]
done, thanks a lot!

**Pull request merged**
