### PR TITLE
Fixed NullPointerException & API-Change

### PR DESCRIPTION
**Pull request by dennisfabri**
1.  Handled a situation where a NullPointerException was occurring.
2.  Made an API-Change to improve method signature

Further changes:
- Updated dependencies

### CODE REVIEW

**Comment by steos** [comment]
Thank you very much! It looks good to me and I would like to merge this but it seems like there have been formatting changes and code has been moved around in the `JnaFileChooser` class. Can we fix this to have a clean diff?

**Comment by jwcharp** [comment]
Any Ideas on how to preset the file name and extension on a SAVE dialog?

**Comment by jwcharp** [comment]
Hi have forked and added functionality to set the title of the dialog along with preset the default file name and tried to simplify the structure as much as possible.

**Comment by dennisfabri** [comment]
Sorry. I got distracted by other things. I will come back to this when I have the time.

**Comment by dennisfabri** [comment]
Now I reduced the changes to the real modifications with minimal modifications to the code.

**Comment by steos** [comment]
Very cool, thanks for your efforts!

**Pull request merged**
